### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by tayfunyy** [theposeidonas/laravel-parasut-api#3]
Merhabalar tüm bilgierimi sisteme yazmama ragmen 401 hatası vermektedir. Aynı bilgilerle postmanden istek atınca token almaktayım.

**Comment by theposeidonas** [comment]
Merhaba,
.env dosyası içine bilgileri yazarken şu şekilde tırnak içine yazmanız gerekiyor. 
```
PARASUT_USERNAME="demo@parasut.com"  // Username
PARASUT_PASSWORD="XXXXXXXXX"  // Password
PARASUT_COMPANY_ID="123123" // Company ID
PARASUT_CLIENT_ID="XXXXXXXXXXXXXXXXX" // Paraşüt Client ID
PARASUT_CLIENT_SECRET="XXXXXXXXXXXXXXXXX" // Paraşüt Client Secret
PARASUT_REDIRECT_URI="urn:ietf:wg:oauth:2.0:oob" // Paraşüt Redirect URI, değiştirmenize gerek yok
```
Bunun dışında bir hata yaşıyorsanız sorun hesabınız ile alakalı olabilir.

**Comment by tayfunyy** [comment]
O şekilde tanımlı efendim env dosyaları aynı bilgilerle postman auth yapabiliyor.

**Comment by theposeidonas** [comment]
Bu paket aynı Postman gibi request gönderip response'u göstermek üzerine yazıldı. Dökümanları doğru şekilde takip ettiğinizde, bir response (mesela siz 401 status kodlu bir response almışsınız) gösteriyorsa işini doğru yapıyordur. Pakette bir hata olması için error throw etmesi gerekiyor.

Auth işlemi Paraşüt tarafında yapılır, 401 Unauthorized hatasını da Paraşüt verir. Bu sebeple benim size yardımcı olabileceğim bir durum söz konusu değil. Paraşüt ile iletişime geçerseniz onlar size neden 401 aldığınızı söyleyecektir.
